from __future__ import annotations
import copy,hashlib,json,subprocess,sys,tempfile
from pathlib import Path
sys.path.insert(0,str(Path(__file__).parent))
from gemini_interactions_provider import GeminiInteractionsProvider,RawTransportResponse,TOOL_SCHEMAS,LOCKED_MODEL,validate_metadata_response
from protocol_projection import TOOL_ALLOWLIST,ProviderError,canonical_json,turn_protocol_error

def usage(i=10,o=2,t=3):return {'total_input_tokens':i,'total_output_tokens':o,'total_thought_tokens':t,'total_tokens':i+o+t,'total_tool_use_tokens':0}
def base(status,steps,rid='int_1',model=LOCKED_MODEL,u='DEFAULT'):
 x={'id':rid,'model':model,'object':'interaction','status':status,'steps':steps}
 if u=='DEFAULT':u=usage()
 if u is not None:x['usage']=u
 return x
call=base('requires_action',[{'type':'thought','signature':'sig_A'},{'type':'function_call','id':'call_A','name':'read_file','arguments':{'path':'spec.json'}}],u=usage(100,4,7))
final=base('completed',[{'type':'thought','signature':'sig_B','summary':[]},{'type':'model_output','content':[{'type':'text','text':'done'}]}],rid='int_2',u=usage(140,5,2))
multi=base('requires_action',[{'type':'thought','signature':'sig_M'},{'type':'function_call','id':'call_M1','name':'list_files','arguments':{}},{'type':'function_call','id':'call_M2','name':'run_verifier','arguments':{}}],rid='int_m',u=usage(50,3,1))
cases={'valid_single_call':call,'valid_final':final,'valid_multiple_calls':multi}
def mut(name,src,fn):x=copy.deepcopy(src);fn(x);cases['invalid_'+name]=x
mut('builtin_step',call,lambda x:x.__setitem__('steps',[{'type':'google_search_call','id':'g1','arguments':{'queries':['x']}}]));mut('thought_no_signature',final,lambda x:x['steps'][0].pop('signature'));mut('thought_empty_signature',final,lambda x:x['steps'][0].__setitem__('signature',''));mut('thought_bad_signature_type',final,lambda x:x['steps'][0].__setitem__('signature',3));mut('model_mismatch',final,lambda x:x.__setitem__('model','gemini-flash-latest'));mut('missing_usage',final,lambda x:x.pop('usage'));mut('missing_input_usage',final,lambda x:x['usage'].pop('total_input_tokens'));mut('missing_output_usage',final,lambda x:x['usage'].pop('total_output_tokens'));mut('negative_input_usage',final,lambda x:x['usage'].__setitem__('total_input_tokens',-1));mut('float_output_usage',final,lambda x:x['usage'].__setitem__('total_output_tokens',2.5));mut('negative_thought_usage',final,lambda x:x['usage'].__setitem__('total_thought_tokens',-2));mut('incomplete',final,lambda x:x.__setitem__('status','incomplete'));mut('failed',final,lambda x:x.__setitem__('status','failed'));mut('cancelled',final,lambda x:x.__setitem__('status','cancelled'));mut('duplicate_call',multi,lambda x:x['steps'][2].__setitem__('id','call_M1'));mut('nontext_output',final,lambda x:x['steps'][1].__setitem__('content',[{'type':'image','data':'AA'}]));mut('content_not_list',final,lambda x:x['steps'][1].__setitem__('content',{'type':'text','text':'x'}));mut('text_not_string',final,lambda x:x['steps'][1]['content'][0].__setitem__('text',7));mut('requires_no_call',call,lambda x:x.__setitem__('steps',[{'type':'thought','signature':'s'}]));mut('completed_with_call',call,lambda x:x.__setitem__('status','completed'));mut('unexpected_summary',final,lambda x:x['steps'][0].__setitem__('summary',[{'type':'text','text':'hidden'}]));mut('summary_not_list',final,lambda x:x['steps'][0].__setitem__('summary',{}));mut('unknown_tool',call,lambda x:x['steps'][1].__setitem__('name','shell'));mut('empty_call_id',call,lambda x:x['steps'][1].__setitem__('id',''));mut('arguments_list',call,lambda x:x['steps'][1].__setitem__('arguments',[]));mut('arguments_null',call,lambda x:x['steps'][1].__setitem__('arguments',None));mut('missing_response_id',final,lambda x:x.pop('id'));mut('empty_response_id',final,lambda x:x.__setitem__('id',''));mut('steps_not_list',final,lambda x:x.__setitem__('steps',{}));mut('scalar_step',final,lambda x:x.__setitem__('steps',[7]));mut('errors_present',final,lambda x:x.__setitem__('errors',[{'code':'x','message':'bad'}]));mut('unknown_step',final,lambda x:x.__setitem__('steps',[{'type':'future_step'}]))
raw_cases={k:json.dumps(v,ensure_ascii=False,sort_keys=True,indent=2) for k,v in sorted(cases.items())}
class One:
 def __init__(self,raw):self.raw=raw
 def __call__(self,p):return RawTransportResponse(self.raw,json.loads(self.raw))
class Seq:
 def __init__(self,rs):self.rs=list(rs);self.payloads=[]
 def __call__(self,p):self.payloads.append(json.loads(canonical_json(p)));raw=self.rs.pop(0);return RawTransportResponse(raw,json.loads(raw))
def msgs():return [{'role':'system','content':'SYS'},{'role':'user','content':'TASK'}]
def norm(t):return {'decision':'ACCEPT','response_id':t.response_id,'model_id':t.model_id,'text':t.text,'calls':[{'id':c.call_id,'name':c.name,'arguments':c.arguments} for c in t.tool_calls],'input_tokens':t.input_tokens,'controller_output_tokens':t.output_tokens,'raw_sha256':t.raw_response_sha256,'controller_protocol_error':turn_protocol_error(t)}
py={}
for name,raw in raw_cases.items():
 p=GeminiInteractionsProvider(transport=One(raw))
 try:py[name]=norm(p.generate(msgs(),TOOL_ALLOWLIST))
 except ProviderError as e:py[name]={'decision':'REJECT','observed':bool(e.output_observed),'retryable':bool(e.retryable)}
node=r'''const fs=require('fs'),crypto=require('crypto');const LOCKED='gemini-3.8-flash',TOOLS=new Set(['list_files','read_file','write_file','run_verifier']);const sha=s=>crypto.createHash('sha256').update(Buffer.from(s,'utf8')).digest('hex');function si(u,k,req=true){if(!(k in u)){if(req)throw Error();return 0}if(!Number.isInteger(u[k])||u[k]<0)throw Error();return u[k]}function parse(raw){let r;try{r=JSON.parse(raw)}catch{return {decision:'REJECT',observed:false,retryable:false}}const steps=Array.isArray(r.steps)?r.steps:null,observed=!!(steps&&steps.length);try{if(Array.isArray(r.errors)&&r.errors.length)throw Error();if(!r.usage||typeof r.usage!=='object')throw Error();const it=si(r.usage,'total_input_tokens'),vo=si(r.usage,'total_output_tokens'),th=si(r.usage,'total_thought_tokens',false);if(typeof r.id!=='string'||!r.id||r.model!==LOCKED||!steps)throw Error();const calls=[],texts=[],ids=new Set();for(const s of steps){if(!s||typeof s!=='object')throw Error();if(s.type==='thought'){if(typeof s.signature!=='string'||!s.signature)throw Error();if(s.summary!==undefined&&!(Array.isArray(s.summary)&&s.summary.length===0))throw Error()}else if(s.type==='function_call'){if(!TOOLS.has(s.name)||typeof s.id!=='string'||!s.id||!s.arguments||typeof s.arguments!=='object'||Array.isArray(s.arguments)||ids.has(s.id))throw Error();ids.add(s.id);calls.push({id:s.id,name:s.name,arguments:s.arguments})}else if(s.type==='model_output'){if(!Array.isArray(s.content))throw Error();for(const p of s.content){if(!p||p.type!=='text'||typeof p.text!=='string')throw Error();texts.push(p.text)}}else throw Error()}if(calls.length){if(r.status!=='requires_action')throw Error()}else if(r.status!=='completed')throw Error();return {decision:'ACCEPT',response_id:r.id,model_id:r.model,text:texts.join('\n'),calls,input_tokens:it,controller_output_tokens:vo+th,raw_sha256:sha(raw),controller_protocol_error:calls.length>1?'MULTIPLE_TOOL_CALLS':null}}catch{return {decision:'REJECT',observed,retryable:false}}}const fx=JSON.parse(fs.readFileSync(process.argv[2],'utf8')),out={};for(const k of Object.keys(fx).sort())out[k]=parse(fx[k]);fs.writeFileSync(process.argv[3],JSON.stringify(out));'''
with tempfile.TemporaryDirectory() as d:
 d=Path(d);(d/'fx.json').write_text(json.dumps(raw_cases));(d/'v.js').write_text(node);subprocess.run(['node',str(d/'v.js'),str(d/'fx.json'),str(d/'out.json')],check=True);nd=json.loads((d/'out.json').read_text())
assert py==nd
tr=Seq([raw_cases['valid_single_call'],raw_cases['valid_final']]);p=GeminiInteractionsProvider(transport=tr);first=p.generate(msgs(),TOOL_ALLOWLIST);follow=msgs()+[{'role':'assistant','content':first.text,'tool_call':{'id':'call_A','name':'read_file','arguments':{'path':'spec.json'}}},{'role':'tool','tool_call_id':'call_A','name':'read_file','content':'SPEC'}];p.generate(follow,TOOL_ALLOWLIST)
assert set(tr.payloads[0])=={'model','input','system_instruction','tools','store','background','stream','generation_config'};assert tr.payloads[0]['generation_config']=={'thinking_level':'high','thinking_summaries':'none','max_output_tokens':12000,'tool_choice':'auto'};assert [x['name'] for x in tr.payloads[0]['tools']]==list(TOOL_ALLOWLIST);assert 'previous_interaction_id' not in tr.payloads[0] and 'previous_interaction_id' not in tr.payloads[1]
expect=[{'type':'user_input','content':[{'type':'text','text':'TASK'}]},{'type':'thought','signature':'sig_A'},{'type':'function_call','id':'call_A','name':'read_file','arguments':{'path':'spec.json'}},{'type':'function_result','name':'read_file','call_id':'call_A','is_error':False,'result':[{'type':'text','text':'SPEC'}]}];assert tr.payloads[1]['input']==expect
tm=GeminiInteractionsProvider(transport=One(raw_cases['valid_multiple_calls'])).generate(msgs(),TOOL_ALLOWLIST);assert len(tm.tool_calls)==2 and turn_protocol_error(tm)=='MULTIPLE_TOOL_CALLS';assert py['valid_single_call']['controller_output_tokens']==11
mdraw=json.dumps({'name':'models/gemini-3.8-flash'},indent=2);assert validate_metadata_response(RawTransportResponse(mdraw,json.loads(mdraw)))['model']==LOCKED_MODEL
try:validate_metadata_response(RawTransportResponse('{"name":"models/gemini-flash-latest"}',{'name':'models/gemini-flash-latest'}));raise AssertionError()
except ProviderError:pass
report={'schema':'neutral.adapter-qualification.v2','status':'PASS','fixture_cases':len(raw_cases),'accepted':sum(x['decision']=='ACCEPT' for x in py.values()),'rejected':sum(x['decision']=='REJECT' for x in py.values()),'python_node_differential_identity':True,'request_surface_exact':True,'stateless_exact_replay':True,'multiple_calls_preserved_then_controller_rejected':True,'thought_tokens_in_controller_output_budget':True,'metadata_identity_strict':True,'no_network_generation':True,'fixture_sha256':hashlib.sha256(json.dumps(raw_cases,sort_keys=True,separators=(',',':')).encode()).hexdigest()}
print(json.dumps(report,sort_keys=True,separators=(',',':')))
